general {
    lock_cmd = pidof hyprlock || hyprlock          # no lanza una segunda instancia si ya está activo
    unlock_cmd = pkill -USR1 hyprlock              # desbloquea desde D-Bus
    before_sleep_cmd = loginctl lock-session        # bloquea antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on      # enciende pantalla al despertar
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# ── 1. Atenuar pantalla a los 5 min ───────────────────────────
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 20%          # guarda brillo actual y baja al 20%
    on-resume = brightnessctl -r                   # restaura brillo guardado
}

# ── 2. Bloquear pantalla a los 10 min ─────────────────────────
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# ── 3. Apagar pantalla 30 s después del bloqueo ───────────────
listener {
    timeout = 630
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# ── 4. Suspender a los 30 min ─────────────────────────────────
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
