wallpaper {
    monitor = HDMI-A-1
    path = /home/andres/images/wallpaper.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/andres/images/wallpaper.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = LVDS-1
    path = /home/andres/images/wallpaper.png
    fit_mode = cover
}

splash = false
ipc = on
